#!/bin/bash # The interpreter used to execute the script

# Lines beginning with #SBATCH specify your computing resources and other logistics about how to run your job.
#SBATCH --account=mdatascience_team
#SBATCH --time=12:00
#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --mem=1g
#SBATCH --job-name=example_job
#SBATCH --output=example_output.out
#SBATCH --mail-user=lukeyang@umich.edu
#SBATCH --mail-type=BEGIN,END

module load python/3.11.5

python3 train.py --dataroot datasets/vangogh2photo/ --cuda